V0.9.26 hiroba
RCOSDP/weko-document pull request #3
Opened 2024-07-26 07:09 UTC by kanon-yoneji

2024-07-26 09:47 UTC, asuzuki1 requested changes

2024-07-26 09:47 UTC, asuzuki1 commented on docs/spec/USER_3_2.md
> +                ・設定されているロールに所属しないユーザーには、<Download>ボタンを表示しない。
`<Download>`の部分がタグ扱いされてしまい表示されないようです。
「～経過した場合、ボタンを表示する。」のように表示されてしまいます。
エスケープするか、`<>`ではなく`「」`などを使用するようにしてください。

ここ以外にも同様の部分があるので併せて修正お願いします。

2024-07-29 01:17 UTC, kanon-yoneji commented on docs/spec/USER_3_2.md
> +                ・設定されているロールに所属しないユーザーには、<Download>ボタンを表示しない。
【ダウンロード（Download）】に修正しました。

2024-07-29 01:58 UTC, asuzuki1 approved these changes

2024-12-09 05:18 UTC, merged